{% set name = "rtl-sdr" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.post20231004

source:
  url: https://github.com/osmocom/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ee10a76fe0c6601102367d4cdf5c26271e9442d0491aa8df27e5a9bf639cff7c
  patches:
    - 0001-Add-commits-since-0.6.0-through-2023-08-21.patch
    - 0002-count-live-transfers-before-close.patch
    - 0003-add-libusb-lib-directories-in-cmake-for-macos.patch
    - 0004-call-interrupt_event_handler-in-cancel_async.patch
    - 0005-open-with-file-descriptor.patch
    - 0006-l-band-lock-optimizations.patch
    - 0007-Add-rtl-sdr-blog-features.patch
    - 0008-follow-keenerd-and-don-t-stop-the-i2c-repeater-on-tu.patch
    - 0009-fix-rtl_tcp-on-macos.patch
    - 0010-fix-rtl_tcp-error-on-windows-when-hints-not-initiali.patch
    - 0011-Set-version-for-conda-forge.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('rtl-sdr', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    # libudev CDT needed to link against libusb through uhd on linux CentOS 6
    # libusb uses the conda-forge libudev package for CentOS 7
    - {{ cdt('libudev-devel') }}  # [linux and cdt_name=='cos6']
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - libusb
    # restrict to cos6-compatible libusb (and libudev)
    - libusb-cos6  # [linux and cdt_name=='cos6']
    - pthreads-win32  # [win]
  run:
    - pthreads-win32  # [win]

test:
  commands:
    # make it possible to check !ERRORLEVEL! after || on Windows
    - setlocal EnableDelayedExpansion  # [win]

    # verify that executables get installed
    {% set cmds = ["rtl_adsb", "rtl_biast", "rtl_eeprom", "rtl_fm", "rtl_power"] %}
    {% set cmds = cmds + ["rtl_sdr", "rtl_tcp", "rtl_test"] %}
    {% for cmd in cmds %}
    - {{ cmd }} -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - {{ cmd }} -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    {% endfor %}

    # verify that headers get installed
    - test -f $PREFIX/include/rtl-sdr.h  # [not win]
    - test -f $PREFIX/include/rtl-sdr_export.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\rtl-sdr.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\rtl-sdr_export.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/librtlsdr${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\rtlsdr.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\rtlsdr.lib exit 1  # [win]

about:
  home: https://osmocom.org/projects/rtl-sdr/wiki
  license: GPL-2.0-or-later AND LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Library for using an Realtek RTL2832-based DVB dongle as an SDR receiver'
  description: |
    DVB-T dongles based on the Realtek RTL2832U can be used as a cheap SDR, since the
    chip allows transferring the raw I/Q samples to the host, which is officially used
    for DAB/DAB+/FM demodulation. The possibility of this has been discovered by Eric
    Fry (http://rtlsdr.org/#history_and_discovery_of_rtlsdr).
  doc_url: https://osmocom.org/projects/rtl-sdr/wiki
  dev_url: https://osmocom.org/projects/rtl-sdr/repository

extra:
  recipe-maintainers:
    - ryanvolz
