{% set name = "rtl-sdr" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/osmocom/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d69943eb32df742bc38a00ce6615e41250fd57851174e5ff916ec31e9e9e68e9
  patches:
    - 0001-add-libusb-lib-directories-in-cmake-for-macos.patch
    - 0002-open-with-file-descriptor.patch
    - 0003-l-band-lock-optimizations.patch
    - 0004-Add-rtl-sdr-blog-features.patch
    - 0005-follow-keenerd-and-don-t-stop-the-i2c-repeater-on-tu.patch
    - 0006-Handle-USB-bulk-transfer-timeouts.patch
    - 0007-Ignore-transfer-error-when-not-in-progress-already-c.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('rtl-sdr', max_pin='x') }}
  # instructions for manually linking udev rules
  post-link: post-link  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - libusb
    - winpthreads-devel  # [win]

test:
  commands:
    # make it possible to check !ERRORLEVEL! after || on Windows
    - setlocal EnableDelayedExpansion  # [win]

    # verify that executables get installed
    - rtl_adsb -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_biast -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_eeprom -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_fm -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_power -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_sdr -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_tcp -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - rtl_test -h || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]

    - rtl_adsb -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_biast -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_eeprom -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_fm -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_power -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_sdr -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_tcp -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    - rtl_test -h || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]

    # verify that headers get installed
    - test -f $PREFIX/include/rtl-sdr.h  # [not win]
    - test -f $PREFIX/include/rtl-sdr_export.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\rtl-sdr.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\rtl-sdr_export.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/librtlsdr${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\rtlsdr.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\rtlsdr.lib exit 1  # [win]

about:
  home: https://osmocom.org/projects/rtl-sdr/wiki
  license: GPL-2.0-or-later AND LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Library for using an Realtek RTL2832-based DVB dongle as an SDR receiver'
  description: >
    DVB-T dongles based on the Realtek RTL2832U can be used as a cheap SDR, since the chip allows transferring the raw I/Q samples to the host, which is officially used for DAB/DAB+/FM demodulation. The possibility of this has been discovered by Eric Fry (http://rtlsdr.org/#history_and_discovery_of_rtlsdr).

    For Linux users of `rtl-sdr`, you will likely want to link the provided udev rule into your system installation in order for the hardware to have the correct permissions:

        sudo ln -s $CONDA_PREFIX/lib/udev/rules.d/rtl-sdr.rules /etc/udev/rules.d/
        sudo udevadm control --reload
        sudo udevadm trigger

    You may have to restart for this change to take effect.

    Even though the Linux kernel's built-in DVB-T module that would normally claim the device should be unloaded automatically, you might also want to blacklist the DVB-T module by running:

        sudo ln -s $CONDA_PREFIX/etc/modprobe.d/rtl-sdr-blacklist.conf /etc/modprobe.d/
        sudo modprobe -r $(cat $CONDA_PREFIX/etc/modprobe.d/rtl-sdr-blacklist.conf | sed -n -e 's/^blacklist //p')
  doc_url: https://osmocom.org/projects/rtl-sdr/wiki
  dev_url: https://gitea.osmocom.org/sdr/rtl-sdr

extra:
  recipe-maintainers:
    - ryanvolz
